# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Configuracion', '0001_initial'),
        ('Clientes', '0003_tb_cliente_fechacobromensual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_ingresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default='0', max_length=30, null=True)),
                ('descripcion', models.TextField(default='Sin Descripcion', max_length=30000, null=True)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Clientes.tb_cliente')),
                ('formaDePago', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_formasDePago')),
                ('tipoIngreso', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_tipoIngreso')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingresos',
                'managed': True,
            },
        ),
    ]
