# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_profile',
            name='birthdayDate',
        ),
        migrations.RemoveField(
            model_name='tb_profile',
            name='houseTlf',
        ),
        migrations.RemoveField(
            model_name='tb_profile',
            name='image',
        ),
        migrations.AddField(
            model_name='tb_profile',
            name='montoAcumulado',
            field=models.FloatField(default='0', max_length=30, null=True),
        ),
    ]
