# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-29 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20180403_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_profile',
            name='montoMensualidad',
            field=models.CharField(default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tb_profile',
            name='tipoUser',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Programador', 'Programador')], default='Administrador', max_length=30),
        ),
    ]
