# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProyecto', models.CharField(default='Sin Datos', max_length=30, null=True)),
                ('dateInicio', models.CharField(default='abc-123', max_length=30, null=True)),
                ('logo', models.ImageField(default='Null', null=True, upload_to='proyectos/logo/')),
                ('dateCreate', models.DateField(auto_now=True)),
                ('developer', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='UserProfile.tb_profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'proyectos',
            },
        ),
    ]
