# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tb_proyectos',
            new_name='tb_proyecto',
        ),
    ]
