# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0002_auto_20180322_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_proyecto',
            name='dateInicio',
            field=models.DateField(default='1995-04-19', null=True),
        ),
    ]
