# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proyectos', '0003_auto_20180322_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEmpresa', models.CharField(default='Sin Datos', max_length=30, null=True)),
                ('mailEmpresa', models.EmailField(default='sin@datos.com', max_length=30, null=True)),
                ('Nacionalidad', models.CharField(default='Sin Datos', max_length=30, null=True)),
                ('namePersonaEncargada', models.CharField(default='Sin Datos', max_length=30, null=True)),
                ('montoMensualidad', models.CharField(default='0', max_length=30, null=True)),
                ('urlProject', models.URLField(default='', max_length=3000, null=True)),
                ('DateInicioContrato', models.DateField(default='1995-04-19', null=True)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('Project', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='Proyectos.tb_proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'Clientes',
            },
        ),
    ]
