# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_cliente',
            name='Cuit',
            field=models.CharField(default='Sin Datos', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tb_cliente',
            name='RazonSociol',
            field=models.CharField(default='Sin Datos', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tb_cliente',
            name='TelefonoContacto',
            field=models.CharField(default='+00000', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tb_cliente',
            name='VendedorAsignado',
            field=models.CharField(default='Sin Datos', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_cliente',
            name='Nacionalidad',
            field=models.CharField(default='Sin Datos', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_cliente',
            name='nameEmpresa',
            field=models.CharField(default='Sin Datos', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_cliente',
            name='namePersonaEncargada',
            field=models.CharField(default='Sin Datos', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_cliente',
            name='urlProject',
            field=models.URLField(default='http://179.43.123.41:8000/', max_length=3000, null=True),
        ),
    ]
