# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_auto_20180323_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_cliente',
            name='FechaCobroMensual',
            field=models.DateField(default='1995-04-19', null=True),
        ),
    ]
