# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-23 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_tb_cliente_fechacobromensual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_cliente',
            name='RazonSociol',
        ),
        migrations.AddField(
            model_name='tb_cliente',
            name='RazonSocial',
            field=models.CharField(default='Sin Datos', max_length=300, null=True),
        ),
    ]
