# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-23 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_auto_20180523_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_cliente',
            old_name='RazonSocial',
            new_name='RazonSociol',
        ),
    ]
